# Generated by Django 3.1.5 on 2021-01-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=30000)),
                ('typeof', models.CharField(max_length=15)),
            ],
        ),
    ]
