# Generated by Django 3.1.5 on 2021-01-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210112_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='subHeading',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='heading',
            field=models.CharField(max_length=125),
        ),
    ]
